server:
    port: 8080

spring:
    application:
        name: api
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-container:3306/classic_models?serverTimezone=Asia/Seoul
        username: root
        password: 1234

    jpa:
        generate-ddl: false
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                globally_quoted_identifiers: false
                format_sql: true
        hibernate:
            ddl-auto: none